<!DOCTYPE html>
<html lang="pt-br">
<head>
    <meta charset="UTF-8">
    <title></title>
</head>
<body>
<?php
    //Fazer a conexão
    $servidor = "localhost";
    $nomeDeUsusario = "root";
    $senha = "Valdinete1234";
    $banco = "myDB";

    try{
        $conexao = new PDO("mysql:host=$servidor;dbname=$banco", $nomeDeUsusario, $senha);

        $conexao->setAttribute(PDO::ATTR_ERRMODE, PDO::ERRMODE_EXCEPTION);
        echo "Conectado com sucesso";
    }catch (PDOException $exception){
        echo "Erro de conexão: ".$exception->getMessage();
    }
    //Fazer a conexão

    //Fechar a conexão
    //$conexao = null;
    //Fechar a conexão

    //Criar banco de dados
    /*
    $sql = "create database myDB";

    try{
        $conexao->exec($sql);
        echo "Banco de dados criado com sucesso";
    }catch (PDOException $exception){
        echo "Erro ao criar o banco: ".$exception->getMessage();
    }
    */
    //Criar banco de dados

    //Criar tabelas
    /*
    $sql = "create table MyGuests(
    id int(6) unsigned auto_increment primary key,
    primeiro_nome varchar(30) not null,
    sobrenome varchar(30) not null,
    email varchar(50),
    data_registro timestamp default current_timestamp on update current_timestamp
    );";

    try{
        $conexao->exec($sql);
        echo "Tabela MyGuests criada com sucesso";
    }catch (PDOException $exception){
        echo "Erro ao criar a tabela: ".$conexao->error;
    }
    */
    //Criar tabelas

    //Inserir dados
    /*
    $sql = "insert into MyGuests (primeiro_nome, sobrenome, email) values ('John', 'Doe', 'john@example.com')";

    try{
        $conexao->exec($sql);
        echo "Novo registro criado com sucesso";
    }catch (PDOException $exception){
        echo "Erro ao criar registro: ".$exception->getMessage();
    }
    */
    //Inserir dados

    //Pegar o id do último registro inserido
    //echo "último ID: ".$conexao->lastInsertId();
    //Pegar o id do último registro inserido

    //Inserir vários registros
    /*
    try{
        $conexao->beginTransaction();
        $conexao->exec("insert into MyGuests (primeiro_nome, sobrenome, email) values ('John', 'Doe', 'john@example.com')");
        $conexao->exec("insert into MyGuests (primeiro_nome, sobrenome, email) values ('Mary', 'Moe', 'mary@example.com')");
        $conexao->exec("insert into MyGuests (primeiro_nome, sobrenome, email) values ('Julie', 'Dooley', 'Julie@example.com')");
        $conexao->commit();
        echo "Registros criados com sucesso";
    }catch (PDOException $exception){
        $conexao->rollBack();
        echo "Erro ao criar registros: ".$exception->getMessage();
    }
    */
    //Inserir vários registros

    //Instruções preparadas
    /*
    try{
        $stmt = $conexao->prepare("insert into MyGuests (primeiro_nome, sobrenome, email) values (:primeiro_nome, :sobrenome, :email)");
        $stmt->bindParam(":primeiro_nome", $primeiroNome);
        $stmt->bindParam(":sobrenome", $sobrenome);
        $stmt->bindParam(":email", $email);

        $primeiroNome = "John";
        $sobrenome = "Doe";
        $email = "john@example.com";
        $stmt->execute();

        $primeiroNome = "Mary";
        $sobrenome = "Moe";
        $email = "mary@example.com";
        $stmt->execute();

        $primeiroNome = "Julie";
        $sobrenome = "Dooley";
        $email = "julie@example.com";
        $stmt->execute();

        echo "Novos registros criados com sucesso";
    }catch (PDOException $exception){
        echo "Erro: ".$exception->getMessage();
    }
    */
    //Instruções preparadas

    //Selecionar dados
    /*
    try {
        echo "<table style='border: solid 1px black'><tr><th>Id</th><th>Primeiro nome</th><th>Sobrenome</th></tr>";

        class linhasDaTabela extends RecursiveIteratorIterator
        {
            function __construct($it)
            {
                parent::__construct($it, self::LEAVES_ONLY);
            }

            function current()
            {
                return "<td style='width: 150px; border: 1px solid black;'>" . parent::current() . "</td>"; // TODO: Change the autogenerated stub
            }

            function beginChildren()
            {
                echo "<tr>";
            }

            function endChildren()
            {
                echo "</tr>" . "\n";
            }
        }

        $stmt = $conexao->prepare("select id, primeiro_nome, sobrenome from MyGuests");
        $stmt->execute();

        $resultado = $stmt->setFetchMode(PDO::FETCH_ASSOC);
        foreach (new linhasDaTabela(new RecursiveArrayIterator($stmt->fetchAll())) as $k => $v) {
            echo "$v";
        }
    } catch (PDOException $exception){
        echo "Erro ao selecionar registros: ".$exception->getMessage();
    }
    */
    //Selecionar dados

    //Remover dados
    /*
    try {
        $sql = "delete from MyGuests where id=2";
        $conexao->exec($sql);
        echo "Registro deletado com sucesso";
    }catch (PDOException $exception){
        echo "Erro ao deletar registro: ".$exception->getMessage();
    }
    */
    //Remover dados

    //Atualizar dados
    /*
    $sql = "update MyGuests set sobrenome='Doe' where id=11";

    try{
        $stmt = $conexao->prepare($sql);
        $stmt->execute();
        echo $stmt->rowCount()." registros atualizados com sucesso";
    }catch (PDOException $exception){
        echo "Erro ao atualizar registros: ".$exception->getMessage();
    }
    */
    //Atualizar dados
?>
</body>
</html>